<?php
// v pripade chyb nebo novych hlasek mne kontaktujte 
// na adrese pm@kostax.cz
// dekuji
// Petr Macek

$labels = array();
$labels['vacation'] = 'Dovolená';
$labels['autoreply'] = 'Zapnout aut. odpověď';
$labels['outofoffice'] = 'Automatická odpověď';
$labels['autoreplysubject'] = 'Předmět zprávy';
$labels['autoreplymessage'] = 'Zpráva';
$labels['autoreplybutton'] = 'Ulož';
$labels['mailforward'] = 'Přeposílání';
$labels['aliases'] = 'Alias';
$labels['keepcopy'] = 'Zachovat zde kopii';
$labels['forwardingaddresses'] = 'Přeposlat na';
$labels['forward'] = 'Nastavení přesměrování';
$labels['success_changed'] = 'Nastavení bylo úspěšně změněno';
$labels['failed'] = 'Automatickou odpověď / Přeposílání se nepodařilo nastavit!';
$labels['separate_forward'] = 'Více adres oddělujte čárkou';
$labels['separate_alias'] = 'Víc aliasů  oddělujte čárkou';
?>
