<?php
$labels = array();
$labels['vacation'] = 'Abwesenheit';
$labels['autoresponder'] = 'Abwesenheit';
$labels['autoreply'] = "Automatische Antwort aktiviert";
$labels['outofoffice'] = 'Abwesenheitsnotiz';
$labels['autoreplysubject'] = 'Betreff der automatischen Antwort';
$labels['autoreplymessage'] = 'Nachricht der automatischen Antwort';
$labels['autoreplybutton'] = 'Speichern';
$labels['mailforward'] = 'Weiterleitung';
$labels['keepcopy'] = 'Behalte eine Kopie der Nachrichten';
$labels['forwardingaddresses'] = 'Weiterleitung an';
$labels['forward'] = 'Weiterleitung';
$labels['success_changed'] = 'Einstellungen erfolgreich gespeichert';
$labels['failed'] = 'Fehler beim Speichern';
$messages = array();
$messages['autoresponder'] = 'Abwesenheit';
$messages['vacation'] = 'Abwesenheit';
?>
