<?php
$labels = array();
$labels['vacation'] = 'Vacation';
$labels['outofoffice'] = 'Vacation (Out of Office) Notification';
$labels['autoreply'] = 'Send autoreply to sender?';
$labels['autoreplysubject'] = 'Autoreply subject';
$labels['autoreplymessage'] = 'Autoreply message';
$labels['autoreplybutton'] = 'Save';
$labels['mailforward'] = 'Mail Forwarding';
$labels['keepcopy'] = 'Keep a copy of the mail';
$labels['forwardingaddresses'] = 'Forwarding email addresses:';
$labels['success_enabled'] = 'Vacation succesfully enabled';
$labels['success_disabled'] = 'Vacation succesfully disabled';
$labels['failed'] = 'Setting vacation failed!'
?>