<?php
$labels = array();
$labels['vacation'] = 'Vacation';
$labels['autoreply'] = "Send a notification";
$labels['outofoffice'] = 'Vacation (Out of Office) Notification';
$labels['autoreplysubject'] = 'Autoreply subject';
$labels['autoreplymessage'] = 'Autoreply message';
$labels['autoreplybutton'] = 'Save';
$labels['mailforward'] = 'Mail Forwarding';
$labels['keepcopy'] = 'Keep a copy of the mail';
$labels['forwardingaddresses'] = 'Forward mail to';
$labels['forward'] = 'Forwarding settings';
$labels['success_changed'] = 'Vacation settings succesfully changed';
$labels['failed'] = 'Setting vacation failed!'
?>