<?php
$labels = array();
$labels['vacation'] = 'Wakacje';
$labels['autoresponder2'] = 'Wakacje';
$labels['autoreply'] = "Wyslij powiadomienie";
$labels['outofoffice'] = 'Powiadomienie (Poza Biurem)';
$labels['autoreplysubject'] = 'Temat autoodpowiedzi';
$labels['autoreplymessage'] = 'Tresc autoodpowiedzi';
$labels['autoreplybutton'] = 'Zapisz';
$labels['mailforward'] = 'Przekazanie wiadomosci';
$labels['keepcopy'] = 'Zachowaj kopie wiadomosci';
$labels['forwardingaddresses'] = 'Przekaz wiadomosc na adres';
$labels['forward'] = 'Ustawienia przekazywania';
$labels['success_changed'] = 'Ustawienia autoodpowiedzi skonfigurowano pomyslnie';
$labels['failed'] = 'Blad konfiguracji autoodpowiedzi!';
$labels['aliases'] = 'Aliasy'
?>
